action.configuration.bibcite_entity_contributor_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_contributor_save:
  type: action_configuration_default

action.configuration.bibcite_entity_keyword_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_keyword_save:
  type: action_configuration_default

action.configuration.bibcite_entity_reference_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_reference_save:
  type: action_configuration_default